name: eShopOnWeb Build and Test

on: [push, pull_request, workflow_dispatch]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Setup .NET
#       uses: actions/setup-dotnet@v1
#       with:
#         dotnet-version: '8.0.x'
#         include-prerelease: true

#     - name: Build with dotnet
#       run: dotnet build ./eShopOnWeb.sln --configuration Release
    
#     - name: Test with dotnet
#       run: dotnet test ./eShopOnWeb.sln --configuration Release

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2

#     - name: Setup .NET
#       uses: actions/setup-dotnet@v1
#       with:
#         dotnet-version: '8.0.x'

#     - name: Publish the application
#       run: dotnet publish ./eShopOnWeb.sln --configuration Release --output ./publish

#     - name: Compress published output
#       run: zip -r publish.zip ./publish

#     - name: Copy artifact to EC2 via WinRM
#       uses: gsoft-inc/psrp@v1.0.1
#       with:
#         host: ${{ secrets.EC2_HOST }}
#         username: ${{ secrets.EC2_USERNAME }}
#         password: ${{ secrets.EC2_PASSWORD }}
#         port: 5986
#         script: |
#           Expand-Archive -Path C:\Temp\publish.zip -DestinationPath 'C:\inetpub\wwwroot' -Force
#           Write-Output "Deployment Complete"
#       env:
#         INPUT_FILE: ./publish.zip

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Publish the application
      run: dotnet publish ./src/Web/Web.csproj --configuration Release --output ./publish

    - name: Create zip archive
      run: zip -r publish.zip ./publish

    - name: Upload to EC2 via SCP
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        source: "publish.zip"
        target: "C:/Temp"

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          Stop-WebAppPool -Name "DefaultAppPool"
          Remove-Item -Recurse -Force "C:\inetpub\wwwroot\*"
          Expand-Archive -Path "C:\Temp\publish.zip" -DestinationPath "C:\inetpub\wwwroot"
          Start-WebAppPool -Name "DefaultAppPool"
